name: Assessment workflow container image and manifest push

on:
  push:
    branches: [ "main" ]
    paths:
      - 'assessment/**'
      - 'pipeline/**'
      - .github/workflows/assessment.yml
      - .github/workflows/main.yml

jobs:
  call-main-workflow:
    uses: ./.github/workflows/main.yml
    with:
      workflow_id: assessment
    secrets: inherit

